### ISSUE TITLE
delete method isn't suppoted in category attributes!

### ISSUE THREAD

**Issue by thuongtruong109** [TP-O/e-commerce-server#31]
When I delete the category attribute, the response notification has contents as below. How do I fix them?
![image](https://user-images.githubusercontent.com/88624053/169239404-9e0607ce-039c-4e9c-8080-406735dd7cb7.png)

**Comment by thuongtruong109** [comment]
With that, after clicking the button to create new attributes, the system gets a response that the attribute has been updated, and the attribute also hasn't been added to the database. However, I do not update attributes. I only create new ones!
![Screenshot 2022-05-19 141633](https://user-images.githubusercontent.com/88624053/169241329-b8c48457-0c42-42a5-8bff-7b04f31a11a4.png)
![Screenshot 2022-05-19 141556](https://user-images.githubusercontent.com/88624053/169241353-297eabf4-3cba-4e3e-be0b-05bc0d57096e.png)
![Screenshot 2022-05-19 141528](https://user-images.githubusercontent.com/88624053/169241369-aa3af848-4377-497e-8317-57520e4c061f.png)

**Comment by TP-O** [comment]
Tiếng Việt đê pạn màu mè vãi

**Comment by TP-O** [comment]
Cái API endpoint đó chỉ dùng POST method và áp dụng cho cả update, delete và create luôn.

![image](https://user-images.githubusercontent.com/53143403/169246155-e09c643c-8759-4188-89d1-3b61d0c50b42.png)

Cái trên pạn muốn create 1 attribute thì phải nhét nó zô `create: []`.

![image](https://user-images.githubusercontent.com/53143403/169246211-7ae29f4b-61b6-45eb-9eb1-f3880ded5b93.png)

**Comment by thuongtruong109** [comment]
> Cái API endpoint đó chỉ dùng POST method và áp dụng cho cả update, delete và create luôn.
> 
> ![image](https://user-images.githubusercontent.com/53143403/169246155-e09c643c-8759-4188-89d1-3b61d0c50b42.png)
> 
> Cái trên pạn muốn create 1 attribute thì phải nhét nó zô `create: []`.
> 
> ![image](https://user-images.githubusercontent.com/53143403/169246211-7ae29f4b-61b6-45eb-9eb1-f3880ded5b93.png)

Okee, I understand about them. Thank you, bro😂
